import Head from "next/head";
import { Container } from "react-bootstrap";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create HGA App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="home_page">
        <Container>
          <div className="home_content">
            <div className="home_hearder"></div>
            <div className="home_main">
              <h1>Home Page</h1>
            </div>
          </div>
        </Container>
      </div>
    </>
  );
}
